version: "3"
services:
  site:
    build: .
    working_dir: /usr/src/app
    command: sh -c 'jekyll serve --no-watch --skip-initial-build'
    restart: always
    environment:
      VIRTUAL_HOST: blog.kmdkuk.com
      VIRTUAL_PORT: 4000
      LETSENCRYPT_HOST: blog.kmdkuk.com
      LETSENCRYPT_EMAIL: kouworld0123@gmail.com

networks:
  default:
    external:
      name: shared
