FROM ruby:2.6.5-alpine

ENV APP_HOME /usr/src/app
ENV TZ=Asia/Tokyo
RUN mkdir -p ${APP_HOME}/_site
WORKDIR $APP_HOME

COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

RUN apk update && \
    apk add --no-cache build-base && \
    gem install bundler -v 1.17.2 && \
    bundle install -j$(getconf _NPROCESSORS_ONLN) && \
    find /usr/local/bundle -path '*/gems/*/ext/*/Makefile' -exec dirname {} \; | xargs -n1 -P$(nproc) -I{} make -C {} clean && \
    rm -rf ${GEM_HOME}/cache /usr/local/bundle/cache/* /usr/local/share/.cache/* /var/cache/* /tmp/* && \
    apk del build-base

COPY . ${APP_HOME}

EXPOSE 4000

CMD [ "bundle", "exec", "jekyll", "serve", "--trace", "--host", "0.0.0.0", "--port", "--port", "4000"]
