version: "3"
services:
  site:
    image: kmdkuk/my-blog:latest
    restart: always
    environment:
      VIRTUAL_HOST: blog.kmdkuk.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: blog.kmdkuk.com
      LETSENCRYPT_EMAIL: kouworld0123@gmail.com

networks:
  default:
    external:
      name: shared
