name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kmdkuk/my-blog
          tag_with_ref: true
          cache_froms: kmdkuk/my-blog:latest
  deploy:
    name: deploy aws-ec2
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.DEPLOY_KEY }} # 必須
          public-key: ${{ secrets.DEPLOY_KEY_PUBLIC }} # 必須
      - name: run deploy script
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: bash scripts/deploy.sh
